/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assignment1;

public class App {
    // Return a string with a greeting message of your choice.
    public String getGreeting() {
        return null;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
